### ISSUE TITLE
Use case to sync SQL server with memstate

### ISSUE THREAD

**Issue by AlexSenchenko** [DevrexLabs/memstate#113]
Hi,

Is it valid use case for using to sync memstate with SQL server tables?
How it can be achieved?

**Comment by rofr** [comment]
Hi @AlexSenchenko 

If the question is "Can I use SQL Server as a backing store?" the answer is yes, use the `Memstate.SqlStreamStore` storage provider. This means that the command journal can be persisted to any RDBMS supported by SqlStreamStore

For replication/sync there are a few different patterns that can be applied depending on the requirements. Is it one-way or two-way replication? If one-way, which direction? Sync or async replication? Consistent or eventually consistent? 

I've just activated the discussions feature on GH, can you add a question there elaborate on what kind of replication you have in mind?
