### ISSUE TITLE
host executable

### ISSUE THREAD

**Issue by rofr** [DevrexLabs/memstate#13]
A thin wrapper taking a config file and/or command line args and hosting a server node

**Comment by hagbarddenstore** [comment]
Allow the user to create a simple Main-method to start Memstate server from their own domain model library.

**Comment by hagbarddenstore** [comment]
This is solved by the Memstate.Host project using the defaults. It needs someway to choose the model via configuration.

**Comment by rofr** [comment]
New approach. We won't provide a server application. The user should create a runnable application, add a reference to Memstate.Host and then do a simple to `new HostBuilder().Build().Run();` Fixed by b8c6aa1167cd86befe319fd1c2096217f9b36c10
