### ISSUE TITLE
has easy way to add new Storage Backend like sqlite?

### ISSUE THREAD

**Issue by sgf** [DevrexLabs/memstate#131]
In fact, the bottleneck is the single application, especially the single application that is limited by the client IO. Since Sqlite has very limited support for concurrency. Then MemState should be able to play to its huge advantage.

**Comment by rofr** [comment]
For high availability (and perhaps additional query capacity) you want multiple replicated memstate instances connected to a single storage backend such as EventStore or an RDBMS. If you use the built in FileStorage or were to implement a sqlite storage provider then you can only have a standalone memstate instance. I can't see that that the sqllite engine would add any value over the FileStorage provider becuase the i/o operations are extremely simple. Storage is "just" an append only log that is read from start to finish when an instance starts.

But if you were to implement a storage backend then you would want to inherit from StorageProvider class and implement each IJournalReader, IJournalWriter and IJournalSubscriptionSource. See FileStorageProvider to get an idea of how.

**Comment by sgf** [comment]
At present, I directly operate Sqlite, but because my application is on the client side, my application has very intensive IO access, which is mainly used to synchronize a large amount of data from the api. Because the IO is too intensive, it even affects the normal use of other functional parts of the application except for api synchronization. So actually I need a cache layer that supports addition, deletion, modification and query. And this caching layer is preferably able to automatically write data changes to the storage backend on a regular basis or merge them.
at the same time. I need proper event notification functionality when the api synchronization is complete. Thereby notifying that a specific data source has changed.


memstate seems to meet this need.




> For high availability (and perhaps additional query capacity) you want multiple replicated memstate instances connected to a single storage backend such as EventStore or an RDBMS. If you use the built in FileStorage or were to implement a sqlite storage provider then you can only have a standalone memstate instance. I can't see that that the sqllite engine would add any value over the FileStorage provider becuase the i/o operations are extremely simple. Storage is "just" an append only log that is read from start to finish when an instance starts.
> 
> But if you were to implement a storage backend then you would want to inherit from StorageProvider class and implement each IJournalReader, IJournalWriter and IJournalSubscriptionSource. See FileStorageProvider to get an idea of how.



thanks
