### ISSUE TITLE
Engine.Dispose() hangs when using InMemoryStorageProvider

### ISSUE THREAD

**Issue by rofr** [DevrexLabs/memstate#23]
possible deadlock/locking issue. Investigate SystemTests.Smoke()

**Comment by hagbarddenstore** [comment]
Fixed in commit 94290dcbf24c7ef1b2f5f010a732d28bcf39f4a5.

Added a timeout on the Wait in Engine.Dispose.

**Comment by rofr** [comment]
Deadlock waiting for tasks to complete in Dispose, fixed by 00566ebaf894d1f48e13be8581223565c72878b0
