### ISSUE TITLE
System tests that verify replication across multiple nodes

### ISSUE THREAD

**Issue by rofr** [DevrexLabs/memstate#27]
**Storage Providers**
- EventStore
- PostgreSql

Note: InMemoryStorage and FileStorage do not support multiple nodes.

**Test cases**
- Start multiple engines from an empty store, execute commands on a single engine, verify replication to other engines
- Execute commands on multiple engines, verify that all nodes have identical models
- Start single engine, execute commands, start additional engines, ensure they are in sync

**Comment by hagbarddenstore** [comment]
Something is wrong / slow in the Postgres provider. Sometimes the tests fails because not all events are written.

**Comment by rofr** [comment]
working tests, good enough. closing
