### ISSUE TITLE
Update proxy tests to use interfaces

### ISSUE THREAD

**Issue by rofr** [DevrexLabs/memstate#32]
OrigoDB models derived from MarshalByRefObject and used the built in proxy. Memstate proxy feature is based on System.ReflectionDispatchProxy which can only proxy interfaces. The tests need to be updated to use interface based models.

**Comment by baskar3078** [comment]
Hi Robert, Let me know if I can help on this.

**Comment by rofr** [comment]
@baskar3078  Dang! I fixed this just yesterday. Let me see if I can add some more help-wanted issues so there is more to choose from.
