### ISSUE TITLE
Refactor code for readability and maintenance

### ISSUE THREAD

**Issue by hagbarddenstore** [DevrexLabs/memstate#33]
1. Ensure all files only contain a single type (Inner types allowed).
2. Rename MemstateServer and MemstateClient to follow a convention.
3. Remove unused usings.
4. Remove unused types, methods, properties and fields.

**Comment by hagbarddenstore** [comment]
This issue exists as a reminder.

I suggest that we rename `MemstateServer` and `MemstateClient` to `TcpServer` and `TcpClient`. `TcpClient` is more specific and follows the same naming as `LocalClient`. This allows us to add `HttpClient`, `UdpClient`, etc. in the future without having a weird naming scheme.

For `MemstateServer`, I suggest either `TcpServer` or dropping the `Tcp` prefix and calling it `Server`.

**Comment by rofr** [comment]
I considered TcpServer and TcpClient as these are the most natural names but decided not to use them to avoid confusion with the dotnet framework types in System.Net
