### ISSUE TITLE
Domain Events

### ISSUE THREAD

**Issue by rofr** [DevrexLabs/memstate#5]
Ability to emit domain events when a command executes. Events should propagate to subscribed clients connected to any node. See http://origodb.com/docs/core-0.19/modeling/domain-events/ for context

**Comment by rofr** [comment]
Add an interface that users can apply to their model. Capture in kernel and shoot events if model is
IDomainEventSource

```csharp
interface IDomainEventSource
{
   event Action<IEvent> EventRaised;
}
```

**Comment by hagbarddenstore** [comment]
IDomainEventSource implemented.
