### ISSUE TITLE
Replace XUnit with NUnit Tests

### ISSUE THREAD

**Issue by goblinfactory** [DevrexLabs/memstate#50]
Replace all the Xunit tests with nunit. 

There's no need to have both Xunit and nunit. Nunit appears to have better support for automating .net standard tests in Cake.

**Comment by rofr** [comment]
Agreed. And this is a good opportunity to improve the quality of the tests, both from a what-are-we-testing and "clean code" perspective

**Comment by shubhranshu** [comment]
Hi Guys, I am trying to convert the existing XUnit tests to nunit and so far so good. However, I am unable to make JournalReaderTests pass. I am new to this and wondering if I have missed some documentation or I'd need a setup step of some kind to be able to run the tests. Any help would be much appreciated

**Comment by goblinfactory** [comment]
Hi @rofr been a while since I opened this issue. I'm pretty certain  I opened this so that I could make the change and contribute something useful, but don't remember adding the "help wanted" github tag, I'm guessing you probably tagged it like that? If you did, then @shubhranshu  will need your help with this one. :) ... given the state of the project .. it's complicated and not easy to accept general pull requests without new people knowing all the "what works" and what doesnt, and what shouldnt yet, and what should and never break etc.

**Comment by goblinfactory** [comment]
@rofr I'm not certain that memstate is in a (excuse the pun) 'state' to be able to tag backlog items with help wanted yet ... discussion needed maybe? perhaps a roadmap of what needs to be done to get the project stable and ready from contributions from devs from all skill levels?

**Comment by goblinfactory** [comment]
@shubhranshu your branch of the fork of memstate is even with DevrexLabs:master on your github profile so I couldnt take a look to see what you've done. It would helpful if you could push the experiment/spike you've done to a branch so I can clone your branch and take a look. Also, since I'm not sure yet if @rofr wants me to make this particular change can you let us know if you've spent much time on this, so that if I decide to pick up this work item I don't want to be ungrateful for the effort you've put in?

**Comment by shubhranshu** [comment]
@goblinfactory Thanks for the super quick response. I haven't spent that much time yet. Maybe 15 mins or so. The conversion looks pretty straightforward, just deleting XUnit attributes with NUnit ones and equivalent assertions. So far this looks like a standard refactoring task. I found that XUnit creates a new instance of the test class for each run, which makes writing tests easier but it means NUnit conversion could create side effects.
I haven't pushed my changes yet but I'll post here (?) when I've done so. I think conversion for Memstate.Test can be done wide some reasonable confidence for now. I'll push my changes and let guys see if that looks ok.

**Comment by goblinfactory** [comment]
Main difference is converting anything in a constructor to a `[SetUp] RunBeforeEachTest()`, obvious references, and take into consideration any CICD / if any are being done, read through the project and look for powershell and batch scripts and-or if the project is using Cake or Fake or some other build test runner. (speaking generally of any project not specifically about memstate)

**Comment by goblinfactory** [comment]
Ah, also, before you convert to nunit, are all the existing tests passing in xunit? it's possible a few tests may not be passing because this project is not currently under CICD on appveyor or Azure continuous integration (something I want to do shortly.  So please run all the xunit tests and make sure they all pass, if they don't drop a message here and we can decide how to proceed.

**Comment by shubhranshu** [comment]
Ah yes, I've been using Setup for pre test setup. I'll put more thought into one time setup and setup once i am done converting. All the existing tests are passing (except for the ones which I mentioned already) and .net standard haven't really posed any issue so far. It may be a couple of days before I would have enough time to finish this task though.
I'd be curious to see how the CI/CD would be done.

**Comment by rofr** [comment]
I run the tests from visual studio with either resharper or the builtin test runner. Tests also run on Appveyor for each push to master: https://ci.appveyor.com/project/rofr/memstate

**Comment by rofr** [comment]
Some of the XUnit tests use the IOutputHelper to capture output and send to the console. This is a nuisance and one of the reasons we want to get rid of xunit.

**Comment by rofr** [comment]
But how about you just take the easy ones for starters and we will deal with the complex ones one at a time. It's not necessary to do a PR which replaces all of the xunit tests with nunit tests in one single go.

**Comment by shubhranshu** [comment]
Thanks for the help guys. I have created a pull request for the migration. The changes are scoped to Memstate.Test namespace. Let me know if that looks ok.
Also, is there a Resharper settings file somewhere (external or otehrwise) that I could use ? The Resharper formatting settings are a bit different so I tried not to format anything.

**Comment by rofr** [comment]
done, no xunit references left
