### ISSUE TITLE
Subscription or CommandExecuted event

### ISSUE THREAD

**Issue by Simcon** [DevrexLabs/memstate#70]
Can you clarify the difference between using a subscription:

```
var sub = config.GetStorageProvider().CreateJournalSubscriptionSource();
sub.Subscribe(nextRecord, record =>
{
}
```

and using the CommandExecute event:

```
Engine.CommandExecuted += EngineOnCommandExecuted;
void EngineOnCommandExecuted(JournalRecord journalrecord, bool islocal, IEnumerable<Event> events)
{
}
```

Also whether there's a difference at startup / playback?

**Comment by rofr** [comment]
The responsibility of the StorageProvider is to read/write journalrecords to/from the backing store. The primary consumer of the StorageProvider is the `Engine`. When the `Engine` receives a command it will pass it to a `JournalWriter` which wraps appends it to the journal and assigns a sequential record number. After the record has been persisted the callback (second arg) passed to `Subscribe` is invoked. In the callback, which is defined by the engine, the command is executed. After execution the engine fires the `CommandExecuted` event. The `CommandExecuted` event can be used in the domain code to perform an action after a transaction has completed. For example sending a confirmation email after an order has been created:

```csharp
void OnCommandExecuted(JournalRecord record, bool islocal, IEnumerable<Event> events)
{
   var cmd = record.Command as CreateOrderCommand;
   if (isLocal && cmd != null) SendConfirmationEmail(cmd);
}

engine.CommandExecuted += OnCommandExecuted;
``` 

The `isLocal` argument is true if the command originates from the currently running engine instance, false if it's from a different engine in the cluster.

This event won't fire during replay. Replay happens in `EngineBuilder` before the `Engine` is returned from the `Build()` method. So the user won't be able to add a handler until replay has completed.

Another use of `CommandExecuted` is to capture domain events (third argument) emitted during execution. For example we might want to publish events to a message bus:

```csharp
void OnCommandExecuted(JournalRecord record, bool islocal, IEnumerable<Event> events)
{
   if (isLocal) bus.PublishEvents(events);
}
engine.CommandExecuted += OnCommandExecuted;
``` 
Subscribing to domain events emitted during command execution can instead be done directly on the `Client`. This is to prefer as it will work with either `LocalClient` or `RemoteClient`

```csharp
Client<MyModel> client = Client.For<MyModel>();
client.Subscribe<OrderCreated>(evt => SendConfirmationEmail(evt));
```

To see domain events in action (hooked up to SignalR in an ASP.NET Core web application) check out the https://github.com/devrexlabs/memstate-tutorial repository.

Hope this helps!

**Comment by Simcon** [comment]
Thanks Robert. It took a few reads and some experimentation but I think I understand.

In summary:

```
var sub = config.GetStorageProvider().CreateJournalSubscriptionSource();
```

is _probably not_ what you would usually use as a hook to events since this is concerned with writing to the underlying event store.

Instead use:

```
Client<MyModel> client = Client.For<MyModel>();
client.Subscripe<OrderCreated> …etc...
```

on the client or 

```
Engine.CommandExecuted += EngineOnCommandExecuted;
```

on the engine.

**Comment by rofr** [comment]
> Incidentally, it looks like the tutorial you mentioned isn't complete yet since it doesn't have SignalR hooked up.

Ah, I haven't pushed the last commits yet as I wanted to clean it up a bit first. I'll post here when it's been pushed.

**Comment by rofr** [comment]
@Simcon ok, pushed the signalR bits to the tutorial: https://github.com/devrexlabs/memstate-tutorial
