### ISSUE TITLE
Nuget package older than source

### ISSUE THREAD

**Issue by Simcon** [DevrexLabs/memstate#73]
Can the nuget package be updated to match the source?

**Comment by rofr** [comment]
That sounds very reasonable :)

**Comment by rofr** [comment]
Got the appveyor deployments configured with new access keys, also transfered the packages to the DevrexLabs organisation away from my personal username. Here is the release: https://github.com/DevrexLabs/memstate/releases/tag/0.6.22

**Comment by rofr** [comment]
@Simcon I invited you to the gitter chat, see https://gitter.im
Tell me what you're up to with memstate, maybe I'll get inspired to do some further work!
