### ISSUE TITLE
Improve EngineBuilder error message

### ISSUE THREAD

**Issue by goblinfactory** [DevrexLabs/memstate#79]
Improve the StorageProvider error message so that when a user only references Memstate and follows the getting started guide that the error message will help the user fall into the `pit of success`  i.e. tells the user what to do to resolve the error.

Currently if you only reference memstate and don't include a serializer package, you will get this error after calling Engine.Build<T> ..

<img width="753" alt="Screen Shot 2020-01-19 at 15 23 34" src="https://user-images.githubusercontent.com/1073487/72683489-b2c33400-3acf-11ea-9a05-e7ea3193e7cf.png">

It would be much more helpful if the error message, in addition to the current message could include a message saying something like 

> It looks like you may be missing one of the default serializers. You may need to add a reference to `Memstate.Wire`, `Memstate.JsonNet`, `Memstate.Postgres` or `Memstate.Eventstor`,  or implement your own serializer and include that. For more help see [link to docs] 

The full list can be automatically generated by the `StorageProviders` class.

**Comment by rofr** [comment]
Good call. I think BinarySerializer is back in some netstandard version, also the new System.Json
If we choose one of these as defaults, then we eliminate this problem altogether. Of course, we need to implement them in the core Memstate nuget. What do you think?

**Comment by goblinfactory** [comment]
sounds great, worth a spike branch to test?

**Comment by rofr** [comment]
As long as we are on netstandard <=2.1 an external library is necessary for System.Text.Json
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-overview

I'm reluctant to adding it, any other opinions?

**Comment by goblinfactory** [comment]
I've not dived deep into system.text.json  vs newtonsoft.json.
At a quick glance Newtonsoft on .netstandard 2.0 appears to have no dependancies? Compared to a lot more with `System.Text.Json`.
I'd be leaning towards Newtonsoft.Json, for now, just because memstate user base (well, everyone) is more familiar with Newtonsoft, and later we can upgrade to System.Text.Json if there's a need to? 
<img width="1284" alt="Screen Shot 2020-01-19 at 22 13 35" src="https://user-images.githubusercontent.com/1073487/72689466-9348fd00-3b09-11ea-9e03-78a91aa51643.png">
both require an external package, though most folk see Newtonsoft.Json as really simply saying you have a dependency on doing `Json` things :D like floats or decimals.

**Comment by goblinfactory** [comment]
we should err on what will be easier for us to support moving forward and should be able to swap it out later if needed. If we start working aggresively on improving `memstate` then we should not be afraid to bring up new major versions as and when it makes sense.

**Comment by goblinfactory** [comment]
Also, I think it's easily a reversible decision?

**Comment by rofr** [comment]
BinaryFormatter is netstandard 2.0 so we could use that as default without introducing dependencies. 

The downside is it needs the `Serializable` attribute on all types.

Should we make it default or move the Newtonsoft.Json implementation into the core lib and make that the default?

**Comment by rofr** [comment]
Definitely Newtonsoft over System.Text.Json given all those dependencies. Yikes!

**Comment by goblinfactory** [comment]
Ah, just had a thought, ...snap, you just ruined my idea, saying it needs the `Serializable` atttribute on all types... `shudder`, and .. `yuk`.

I was going to say, if we include `BinaryFormatter` out of the box by default, we can always have a 3 lines "how to" guide that we can take a new user through the process of configuring `memstate` to use a `Json` Serializer, as part of the getting started.

**Comment by goblinfactory** [comment]
busy reading : https://stackoverflow.com/questions/39264293/binary-serialization-without-serializable-attribute

**Comment by goblinfactory** [comment]
we should make wire default. Nice and performant, and allows users to follow the getting started to optionally bring in either JsonNet or System.Text.Json depending on their preferences, and both are ridiculously easy. boom... no [Serializable]'s? Not too familiar with wire.

**Comment by rofr** [comment]
Hadn't considered that option actually, but why not.. Wire is by @rogeralsing (akka.net and protoactor wizard) so pretty solid but guessing it's not actively maintained. Only a single dependency and uncommon so not likely to cause conflict with users other deps.

**Comment by goblinfactory** [comment]
protobuf rulez!

**Comment by goblinfactory** [comment]
The "human readable" is the "reward" you get for sticking with the getting started guide and writing another 3 lines of code :D 
it's all totally up to you (the dev) what you use.

**Comment by goblinfactory** [comment]
also, cof cof... won't hurt that the default out of the box is just a little quick, and compact. In case folk evaluate tools by looking at the default setup.
